Beranda update
GDSC-UM-Indonesia/nextjs_finalproject pull request #29
Opened 2023-06-09 08:10 UTC by fransachmadhw

Update beranda, nambah font tapi bedanya kok tidak terlihat. Coba kalian cek deh

2023-06-09 10:15 UTC, vzrenggamani requested changes
- `HeroBeranda` and `HeroBlog` should be merged into a single components that reusable in other pages instead of creating each one by one in the pages. We can just passing the props of the components instead hardcoded it one-by-one
- Changes on `coreteam.json` should be implemented in other members.
- Use `article` tag for better a11y in article pages.

2023-06-09 10:15 UTC, vzrenggamani commented on src/data/coreteam.json
The changes should be implemented across all of the members to ensure same display combability

2023-06-09 10:15 UTC, vzrenggamani commented on src/pages/blog/[slug].jsx
> +      <div className="container mx-auto prose-full text-white">
```suggestion
      <article className="container mx-auto prose-full text-white">
```

changes to `article` tag instead dull non-semantic components

2023-06-09 10:15 UTC, vzrenggamani commented on src/components/HeroBeranda.jsx
`HeroBeranda` and `HeroBlog` should be merged into a single components that reusable in other pages instead of creating each one by one in the pages.

We can just passing the props of the components instead hardcoded it one-by-one

2023-06-13 01:37 UTC, fransachmadhw commented
itu testing testing component ga jelas ngeganggu banget sumpah

2023-06-13 04:57 UTC, vzrenggamani approved these changes
lgtm

2023-06-13 04:57 UTC, merged